version: '3.6'

services:
  mysql:
    build: ./mysql/
    command: --init-file /data/1.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - moneywhere_mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8085:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123456

  moneywhere-api-user:
    depends_on:
      - mysql
    image: markliu2018/moneywhere-api-user:latest
    env_file: api.env

  moneywhere-fe-user:
    depends_on:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
      API_HOST: https://api.moneywhere.com/api/v1/user-api
    ports:
      - "9097:80"

volumes:
  moneywhere_mysql_data: