version: '3'

services:
  mysql:
    build: ./mysql/
    command: --init-file /data/1.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NWPkVrO2
      MYSQL_DATABASE: moneywhere
    volumes:
      - moneywhere_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pNWPkVrO2 | grep 'mysqld is alive' || exit 1"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/phpmyadmin:latest
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8085:80"

  moneywhere-api-user:
    depends_on:
      mysql:
        condition: service_healthy
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-api-user:latest
    env_file: api.env

  moneywhere-fe-user:
    links:
      - moneywhere-api-user
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-fe-user:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "9097:80"

  moneywhere-fe-user-mobile:
    links:
      - moneywhere-api-user
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-fe-user-mobile:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "9098:80"

volumes:
  moneywhere_mysql_data: