version: '3'

services:
  moneywhere-api-user:
    container_name: moneywhere_api
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-api-user:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-moneywhere}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-78p7gkc1}
      - invite_code=${invite_code:-111111}
    ports:
      - "43742:9092"

  moneywhere-fe-user:
    container_name: moneywhere_fe
    links:
      - moneywhere-api-user
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-fe-user:latest
    restart: always
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43743:80"

  moneywhere-fe-user-mobile:
    container_name: moneywhere_fe_mobile
    links:
      - moneywhere-api-user
    image: registry.cn-hangzhou.aliyuncs.com/moneywhere/moneywhere-fe-user-mobile:latest
    restart: always
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43744:80"