version: '3'

services:
  mysql:
    container_name: moneywhere_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: moneywhere
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=10000',
        '--default-authentication-plugin=mysql_native_password'
    ]
    volumes:
      - moneywhere_mysql_data:/var/lib/mysql
    ports:
      - "43740:3306"

  phpmyadmin:
    container_name: moneywhere_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "43741:80"

  moneywhere-api-user:
    container_name: moneywhere_api
    links:
      - mysql
    image: markliu2018/moneywhere-api-user:latest
    env_file: api.env
    ports:
      - "43742:9092"

  moneywhere-fe-user:
    container_name: moneywhere_fe
    links:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43743:80"

  moneywhere-fe-user-mobile:
    container_name: moneywhere_fe_mobile
    links:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user-mobile:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
    ports:
      - "43744:80"

volumes:
  moneywhere_mysql_data: