version: '3.6'

services:
  moneywhere-api-user:
    image: markliu2018/moneywhere-api-user:latest
    env_file: api.env

  moneywhere-fe-user:
    depends_on:
      - moneywhere-api-user
    image: markliu2018/moneywhere-fe-user:latest
    environment:
      USER_API_HOST: http://moneywhere-api-user:9092
      API_HOST: https://api.moneywhere.com/api/v1/user-api
    ports:
      - "9097:80"

volumes:
  moneywhere_mysql_data: